configuration:
  - Release

image:
  - Ubuntu
  #  - Visual Studio 2017

platform:
  - x64
  - Win32

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - git submodule update --init --recursive
  - ps: |
      $env:GIT_TAG = (git describe HEAD | sed -E "s/-.+$//")
      Update-AppveyorBuild -Version "$env:GIT_TAG-$env:APPVEYOR_BUILD_NUMBER"

before_build:
  - sh: if [ $platform -eq "Win32" ]; then exit 0; fi 
  - sh: set
  - sh: ls -la
  - sh: mk build
  - sh: cd build
  - sh: cmake ..
  - cmd: md c:\projects\milkytracker\build
  - cmd: cd c:\projects\milkytracker\build
  - cmd: if %platform% == Win32 cmake -G "Visual Studio 15 2017" -T v140_xp ..
  - cmd: if %platform% == x64 cmake -G "Visual Studio 15 2017 Win64" -T v140_xp ..

build:
    project: c:\projects\milkytracker\build\MilkyTracker.sln


after_build:
  # https://github.com/chocolatey/chocolatey/issues/431
  - cmake -E remove -f c:\programdata\chocolatey\bin\cpack.exe
  - cpack -C %configuration%

artifacts:
  - path: build\milkytracker*.zip

deploy:
  description: Release $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: k4eMw7MSycoyZwL8VfdAS8ejNXnwhFQ0KOVpif3IqyQDUrOGeGRyCHXm7FsD4kjb
  artifact: /milkytracker.*\.zip/
  prerelease: false
  overwrite: true
  on:
    configuration: Release
    appveyor_repo_tag: true        # deploy on tag push only
