configuration:
  - Release

image:
  - Visual Studio 2020
  - Ubuntu

platform:
  - Win32
  - x64

services:
- docker

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - git submodule update --init --recursive
  - ps: |
      $env:GIT_TAG = (git describe HEAD | sed -E "s/-.+$//")
      Update-AppveyorBuild -Version "$env:GIT_TAG-$env:APPVEYOR_BUILD_NUMBER"

before_build:
  - ps: md c:\projects\milkytracker\build
  - ps: cd c:\projects\milkytracker\build
  - ps: if %platform% == Win32 cmake -G "Visual Studio 14" -T v140_xp ..
  - ps: if %platform% == x64 cmake -G "Visual Studio 14 Win64" -T v140_xp ..

build:
    project: c:\projects\milkytracker\build\MilkyTracker.sln

build_linux:
  - docker run hello-world


after_build:
  # https://github.com/chocolatey/chocolatey/issues/431
  - cmake -E remove -f c:\programdata\chocolatey\bin\cpack.exe
  - cpack -C %configuration%

artifacts:
  - path: build\milkytracker*.zip

deploy:
  description: Release $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: k4eMw7MSycoyZwL8VfdAS8ejNXnwhFQ0KOVpif3IqyQDUrOGeGRyCHXm7FsD4kjb
  artifact: /milkytracker.*\.zip/
  prerelease: false
  overwrite: true
  on:
    configuration: Release
    appveyor_repo_tag: true        # deploy on tag push only
