configuration:
  - Release

image:
  - Ubuntu1604
  - Ubuntu1804
  - Ubuntu2004
  - Ubuntu
  - Visual Studio 2017

platform:
  - x64
  - Win32

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - git submodule update --init --recursive
  - ps: |
      $env:GIT_TAG = (git describe HEAD | sed -E "s/-.+$//")
      Update-AppveyorBuild -Version "$env:GIT_TAG-$env:APPVEYOR_BUILD_NUMBER"

before_build:
  - sh: if [ $PLATFORM == "Win32" ]; then exit 0; fi 
  - sh: ls -la
  - sh: mkdir build
  - sh: cd build
  - sh: sudo apt-get update
  - sh: sudo apt-get install libjack-dev liblhasa-dev librtmidi-dev libsdl2-dev libzzip-dev -y
  - cmd: md c:\projects\milkytracker\build
  - cmd: cd c:\projects\milkytracker\build
  - cmd: if %platform% == Win32 cmake -G "Visual Studio 15 2017" -T v140_xp ..
  - cmd: if %platform% == x64 cmake -G "Visual Studio 15 2017 Win64" -T v140_xp ..

build:
    project: c:\projects\milkytracker\build\MilkyTracker.sln

for:
-
  matrix:
    only:
      - image: Ubuntu
      - image: Ubuntu1604
      - image: Ubuntu1804
      - image: Ubuntu2004

  build_script:
  - sh: cmake -DCMAKE_BUILD_TYPE=Debug ..
  - sh: make
  - sh: cpack -C %configuration% -D CPACK_GENERATOR="ZIP"
  - sh: cd ..
  - sh: unzip build/milkytracker*.zip 
  - sh: echo create AppImage
  - sh: cp -r milkytracker-* Milkytracker-x86_64.AppDir
  - sh: cd Milkytracker-x86_64.AppDir 
  - sh: ln -s bin/milkytracker AppRun
  - sh: mkdir -p usr/lib/x86_64-linux-gnu
  - sh: find /usr/lib |grep rtmidi
  - sh: cp /usr/lib/x86_64-linux-gnu/librtmidi.so.2v5 usr/lib/x86_64-linux-gnu/.
  - sh: cd usr/lib && ln -s x86_64-linux-gnu/librtmidi.so.2v5 && cd ../..
  - sh: cp ../resources/pictures/carton.png milkytracker.png
  - sh: echo -e "[Desktop Entry]\nName=MilkyTracker\nExec=Apprun\nIcon=milkytracker\nType=Application\nCategories=Utility" > myapp.desktop
  - sh: cd .. 
  - sh: wget 'https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage';
  - sh: chmod +x appimagetool*.AppImage
  - sh: ./appimagetool-* Milkytracker-x86_64.AppDir 


after_build:
  # https://github.com/chocolatey/chocolatey/issues/431
  - cmd: cmake -E remove -f c:\programdata\chocolatey\bin\cpack.exe
  - cmd: cpack -C %configuration%

artifacts:
  - path: build\milkytracker*.zip
  - path: milkytracker*.AppImage

deploy:
  description: Release $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: k4eMw7MSycoyZwL8VfdAS8ejNXnwhFQ0KOVpif3IqyQDUrOGeGRyCHXm7FsD4kjb
  artifact: /milkytracker.*\.zip/
  prerelease: false
  overwrite: true
  on:
    configuration: Release
    appveyor_repo_tag: true        # deploy on tag push only
